baseURL = "https://rscribers.mikewk.com/"
languageCode = "en-us"
title = "DATA SCrIbers"
description = "Blog posts about data science"
theme = "tale-hugo"
canonifyurls = true
publishDir = "docs"
assetDir = "static/assets"
paginate = 50
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
