baseURL = "https://rscribers.mikewk.com/"
languageCode = "en-us"
title = "rscribers"
description = "Links to posts about #rstats"
theme = "tale-hugo"
canonifyurls = true
publishDir = "docs"
assetDir = "static/assets"
paginate = 50
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
