baseURL = "https://data-scribers.mikewk.com/"
languageCode = "en-us"
title = "{<span style='color:red'>data sc</span>r<span style='color:red'>i</span><span style='color:red'>bers}"
description = "Blog posts about data science"
theme = "tale-hugo"
canonifyurls = true
publishDir = "docs"
assetDir = "static/assets"
paginate = 50
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
  category = "categories"
  tag = "tags"
